# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f5a851b5d4ea13153390f14c6507e954b4d3e5c6ba0466667005b1c3f7339343090585f3b06614178d2b050ee5ed9b4dcd3d53b5b221f5bf96781e8acd8d158

test:
  secret_key_base: bd4a56aeff3d7aa12cdd3c0399b3eb0bd9021f65bfb34f467e8c7c4656e1f9139b080877a4a51f076a581eb01dfab2baeeb4df95ef919ec00204809e6640cbb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
